version: '3.4'

services:
  webapplication1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  orderstatusservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

